# Experiment
exp_name: add_single_concat_512points
dataset: shapenet
cuda: True
parallel: False


# Model
model: consnet
nlayers: 3
wide: 64

# Hyper Parameter
batch_size: 32
test_batch_size: 32
epochs: 200
use_sgd: True
lr: 0.0003
momentum: 0.9
scheduler: cos

num_points: 512
dropout: 0.5
emb_dims: 1024
k: 20

# Part Segmention
class_choice: None


# Condition
loss: chamfer
mixup: 4 # 1：2 obj emd_mixup 2: rorate 3: alter 4: half + half
eval: False
valid: True







