# Experiment
exp_name: mixup_single_concat_64
dataset: shapenet
cuda: True
parallel: False


# Model
model: consnet
nlayers: 3
wide: 64

# Hyper Parameter
batch_size: 16
test_batch_size: 16
epochs: 100
use_sgd: True
lr: 0.0003
momentum: 0.9
scheduler: cos

num_points: 1024
dropout: 0.5
emb_dims: 1024
k: 20

# Part Segmention
class_choice: None


# Condition
loss: chamfer
mixup: 1 # 1：rotate 2: A + B 3: alter 4: half + half
eval: False
valid: True







